# Generated by Django 2.2.16 on 2021-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='H5WVPS^Jt100(rsR', max_length=20),
        ),
    ]
