# Generated by Django 2.2.16 on 2021-11-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='O^+!Wt!gWo(MG6p', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
