# Generated by Django 2.2.16 on 2021-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='x7PNw_WsUHNmrLONEky', max_length=20, null=True),
        ),
    ]
