# Generated by Django 2.2.16 on 2021-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211111_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='_E3wgWmTAFPAf-)(XsY', max_length=20),
        ),
    ]
